/*
 * Copyright 2018-2026 The Developers Team.
 *
 * Licensed under the Apache License, Version 2.0 (the "License")
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.github.sync.cli.credentials

import com.github.cloudfiles.core.http.Secret
import org.apache.pekko.actor.ActorSystem

import java.nio.file.Path
import scala.concurrent.{ExecutionContext, Future}

/**
  * A trait defining the functionality to manage a file with credentials.
  *
  * The methods defined in this trait correspond to the single commands 
  * supported by the credentials CLI. The commands forward to these methods.
  */
trait CredentialsCommands:
  /**
    * Lists the keys of the credentials contained in a specific credentials
    * file.
    *
    * @param credentialsFile the path to the credentials file
    * @param secret          the [[Secret]] to decrypt the file
    * @param ec              the execution context
    * @param system          the actor system
    * @return a [[Future]] with the output generated by this command
    */
  def listCredentials(credentialsFile: Path, secret: Secret)
                     (using ec: ExecutionContext, system: ActorSystem): Future[String]

  /**
    * Adds a credential to a credentials file. The values stored in the file 
    * are extended by a given key-value pair. If the file already contains a 
    * credential with this key, its value is overridden to the new one. If the
    * credentials file does not exist, it is created now, and the specified
    * credential becomes the new content.
    *
    * @param credentialsFile the path to the credentials file
    * @param secret          the [[Secret]] to decrypt the file
    * @param key             the key of the new credential
    * @param value           the secret value of the credential
    * @param ec              the execution context
    * @param system          the actor system
    * @return a [[Future]] with the output generated by this command
    */
  def addCredential(credentialsFile: Path,
                    secret: Secret,
                    key: String,
                    value: Secret)
                   (using ec: ExecutionContext, system: ActorSystem): Future[String]

  /**
    * Queries the value of a specific credential from the current file. If the
    * value is found, it is printed to the console; otherwise, the result
    * message contains a hint that this credential does not exist.
    *
    * @param credentialsFile the path to the credentials file
    * @param secret          the [[Secret]] to decrypt the file
    * @param key             the key of the new credential
    * @param ec              the execution context
    * @param system          the actor system
    * @return a [[Future]] with the output generated by this command
    */
  def getCredential(credentialsFile: Path,
                    secret: Secret,
                    key: String)
                   (using ec: ExecutionContext, system: ActorSystem): Future[String]

  /**
    * Removes a specific credential from the current file and generates a 
    * message reporting the success of this operation.
    *
    * @param credentialsFile the path to the credentials file
    * @param secret          the [[Secret]] to decrypt the file
    * @param key             the key of the new credential
    * @param ec              the execution context
    * @param system          the actor system
    * @return a [[Future]] with the output generated by this command
    */
  def removeCredential(credentialsFile: Path,
                       secret: Secret,
                       key: String)
                      (using ec: ExecutionContext, system: ActorSystem): Future[String]
