/*
 * Copyright 2018-2026 The Developers Team.
 *
 * Licensed under the Apache License, Version 2.0 (the "License")
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.github.sync.cli.credentials

import com.github.cloudfiles.core.http.Secret
import com.github.sync.FileTestHelper
import org.apache.pekko.actor.ActorSystem
import org.mockito.Mockito.*
import org.scalatest.flatspec.AsyncFlatSpec
import org.scalatest.matchers.should.Matchers
import org.scalatest.{Assertion, BeforeAndAfterEach}
import org.scalatestplus.mockito.MockitoSugar

import java.io.ByteArrayOutputStream
import java.nio.file.{Files, Paths}
import scala.concurrent.{ExecutionContext, Future}

object CredentialsSpec:
  /** The path to the credentials file used by tests. */
  private val TestCredentialsPath = Paths.get("path", "to", "my", "credentials.store")

  /** The secret for the encrypted file storage used by tests. */
  private val TestSecret = Secret("credentials-encryption-secret")

  /** A string that is returned by mocked commands. */
  private val CommandResult = "The output generated by the test command."

  /** A future with the result of asynchronous command execution. */
  private val FutureCommandResult = Future.successful(CommandResult)
end CredentialsSpec

/**
  * Test class for [[Credentials]].
  */
class CredentialsSpec extends AsyncFlatSpec with BeforeAndAfterEach with Matchers with MockitoSugar
  with FileTestHelper:

  import CredentialsSpec.*

  override protected def afterEach(): Unit =
    tearDownTestFile()
    super.afterEach()

  /** An implicit actor system for invoking the mock commands. */
  given mockActorSystem: ActorSystem = mock

  /**
    * Invokes the given credentials object with a specific command
    * configuration and verifies the expected result.
    *
    * @param credentials the credentials object
    * @param cmdConfig   the command configuration
    * @return the result of the test
    */
  private def checkCommandExecution(credentials: CredentialsTestImpl,
                                    cmdConfig: CredentialsParameterManager.CommandConfig): Future[Assertion] =
    credentials.runApp(cmdConfig) map : result =>
      result should be(CommandResult)

  /**
    * Executes the credentials manager CLI application with the provided
    * command line arguments and captures the output it prints. The output is
    * returned as a string.
    *
    * @param args the command line arguments
    * @return the output generated by the application
    */
  private def runAndCaptureOut(args: Array[String]): String =
    val out = new ByteArrayOutputStream
    Console.withOut(out):
      Credentials.main(args)
    new String(out.toByteArray)

  "Credentials" should "handle the list command" in :
    val listConfig = CredentialsParameterManager.ListCommandConfig(TestCredentialsPath, TestSecret)
    val credentials = new CredentialsTestImpl
    when(credentials.commands.listCredentials(TestCredentialsPath, TestSecret)).thenReturn(FutureCommandResult)

    checkCommandExecution(credentials, listConfig)

  it should "handle the add command" in :
    val addConfig = CredentialsParameterManager.AddCommandConfig(
      credentialsFilePath = TestCredentialsPath,
      secret = TestSecret,
      key = "someCredentialsKey",
      value = Secret("someSecretValue")
    )
    val credentials = new CredentialsTestImpl
    when(credentials.commands.addCredential(TestCredentialsPath, TestSecret, addConfig.key, addConfig.value))
      .thenReturn(FutureCommandResult)

    checkCommandExecution(credentials, addConfig)

  it should "handle the get command" in :
    val getConfig = CredentialsParameterManager.GetCommandConfig(
      credentialsFilePath = TestCredentialsPath,
      secret = TestSecret,
      key = "someCredentialsKey"
    )
    val credentials = new CredentialsTestImpl
    when(credentials.commands.getCredential(TestCredentialsPath, TestSecret, getConfig.key))
      .thenReturn(FutureCommandResult)

    checkCommandExecution(credentials, getConfig)

  it should "handle the remove command" in :
    val removeConfig = CredentialsParameterManager.RemoveCommandConfig(
      credentialsFilePath = TestCredentialsPath,
      secret = TestSecret,
      key = "someCredentialsKey"
    )
    val credentials = new CredentialsTestImpl
    when(credentials.commands.removeCredential(TestCredentialsPath, TestSecret, removeConfig.key))
      .thenReturn(FutureCommandResult)

    checkCommandExecution(credentials, removeConfig)

  "main" should "run the application correctly" in :
    val credentialsFile = createPathInDirectory("credentials.crypt")
    val key = "my-credential"
    val args = Array(
      CredentialsParameterManager.CommandAddCredential,
      s"--${CredentialsParameterManager.CredentialsFileOption}",
      credentialsFile.toString,
      s"--${CredentialsParameterManager.SecretOption}",
      TestSecret.secret,
      s"--${CredentialsParameterManager.KeyOption}",
      key,
      s"--${CredentialsParameterManager.ValueOption}",
      "my-secret-value"
    )

    val output = runAndCaptureOut(args)

    Files.isReadable(credentialsFile) shouldBe true
    output should include(s"'$key' was added")

  it should "handle an unknown command" in :
    val UnknownCommand = "do-something!"
    val args = Array(
      UnknownCommand,
      s"--${CredentialsParameterManager.CredentialsFileOption}",
      createPathInDirectory("some-file.crypt").toString,
      s"--${CredentialsParameterManager.SecretOption}",
      TestSecret.secret
    )

    val output = runAndCaptureOut(args)

    output should include(UnknownCommand)
    output should include("Usage: Credentials ")

  it should "provide a generic help screen" in :
    val output = runAndCaptureOut(Array("--help"))

    output should include("command")
    output should include("--file")
    output should not include CredentialsParameterManager.CredentialsFileOption
    output should not include CredentialsParameterManager.SecretOption

  it should "provide a command-specific help screen" in :
    val args = Array(CredentialsParameterManager.CommandAddCredential, "--help")

    val output = runAndCaptureOut(args)

    output should include(CredentialsParameterManager.CredentialsFileOption)
    output should include(CredentialsParameterManager.ValueOption)

  /**
    * A test implementation of the credentials application that uses a mock
    * for the credentials commands. This is used to test whether commands are
    * correctly dispatched.
    */
  private class CredentialsTestImpl(using executionContext: ExecutionContext) extends Credentials(mock):
    override def runApp(config: CredentialsParameterManager.CommandConfig): Future[String] =
      super.runApp(config)

    override def actorSystem: ActorSystem = mockActorSystem

    override def ec: ExecutionContext = executionContext
