/*
 * Copyright 2018-2020 The Developers Team.
 *
 * Licensed under the Apache License, Version 2.0 (the "License")
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.github.sync.cli.oauth

import com.github.sync.cli.oauth.OAuthParameterManager.{CommandConfig, InitCommandConfig, LoginCommandConfig, RemoveCommandConfig}
import com.github.sync.cli.{ActorSystemLifeCycle, ConsoleReader, DefaultConsoleReader, ParameterManager}
import com.github.sync.http.oauth.{OAuthStorageServiceImpl, OAuthTokenRetrieverServiceImpl}

import scala.concurrent.Future

/**
  * An object implementing a CLI with commands related to OAuth identity
  * providers (IDPs).
  *
  * With the commands accepted by this object, some actions can be executed on
  * IDPs that are required, before they can be used with StreamSync, such as
  * registering a new IDP or retrieving a set of tokens.
  *
  * The command line of an invocation must contain exactly one of the commands
  * supported. In addition, there can be a number of options specific to the
  * command.
  */
object OAuth {
  /**
    * The main function of this CLI application. Processes the command line and
    * invokes the desired command. If parameter parsing fails, an error message
    * is printed.
    *
    * @param args the command line arguments
    */
  def main(args: Array[String]): Unit = {
    new OAuth().run(args)
  }
}

/**
  * The implementation class of the CLI extending [[ActorSystemLifeCycle]].
  */
class OAuth extends ActorSystemLifeCycle {

  override val name: String = "OAuthCLI"

  /**
    * @inheritdoc This implementation determines the command to be executed and
    *             runs it.
    */
  override protected def runApp(args: Array[String]): Future[String] = {
    implicit val consoleReader: ConsoleReader = DefaultConsoleReader
    for {params <- ParameterManager.parseParameters(args)
         (cmdConf, _) <- OAuthParameterManager.extractCommandConfig(params)
         result <- executeCommand(cmdConf)
         } yield result //TODO check whether all parameters have been accessed
  }

  /**
    * Executes the command entered on the command line based on the
    * configuration extracted from the options provided.
    *
    * @param cmdConfig     the configuration of the command
    * @param consoleReader the console reader
    * @return a future with the output generated by the command execution
    */
  private def executeCommand(cmdConfig: CommandConfig)(implicit consoleReader: ConsoleReader): Future[String] = {
    val storageService = OAuthStorageServiceImpl
    cmdConfig match {
      case initConfig: InitCommandConfig =>
        OAuthCommands.initIdp(initConfig, storageService)
      case loginConfig: LoginCommandConfig =>
        OAuthCommands.login(loginConfig, storageService, OAuthTokenRetrieverServiceImpl, BrowserHandler(),
          consoleReader)
      case removeConfig: RemoveCommandConfig =>
        OAuthCommands.removeIdp(removeConfig, storageService)
    }
  }
}
